### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by linyukotw** [yohanesgultom/deep-learning-batik-classification#1]
Hello!

Do you have dataset download link? Thank you !

**Comment by yohanesgultom** [comment]
@linyukotw you can get the raw versions [here](https://drive.google.com/open?id=1uFnhO8WXdnyTBxGFy1qlqWU4iPmEF0kH). Since this dataset belongs to Machine Learning and Computer Vision (MLCV) Lab, Faculty of Computer Science, Universitas Indonesia, please make sure to give proper attribution.

**Comment by linyukotw** [comment]
@yohanesgultom Thank you so much! Have a great day

**Comment by adisiji** [comment]
Izin menggunakan datasetnya juga ya mas.
Thanks

**Comment by yohanesgultom** [comment]
@adisiji silahkan, mas. Untuk mempermudah, sitasi ke paper penelitian ini juga sudah saya cantumkan di readme
