### ISSUE TITLE
Requirements.txt error issue

### ISSUE THREAD

**Issue by syenn2896** [yohanesgultom/deep-learning-batik-classification#2]
Halo saya mencoba install requirements.txt yang ada namun timbul error seperti ini. apakah ada solusinya? terima kasih :)
![Capture](https://user-images.githubusercontent.com/23692343/54611290-ff964280-4a99-11e9-8164-708c81ffb479.PNG)

**Comment by yohanesgultom** [comment]
@syenn2896 itu karena anda menggunakan Python 3.x. Seperti yang saya tulis di readme, saya menggunakan Python 2.7.x untuk proyek ini.
